# General parameters; point to input files.
run_type: "Illumina"
samples: "<your-project-directory-name>/sample_data.csv"
output_directory: "<your-project-directory-name>"
reference: "<sequencing-directory>/resources/vc_reference.fasta"
reference_genes: "<sequencing-directory>/resources/cholera_ref_genes/"
recombinant_mask: "<sequencing-directory>/resources/cholera_mask.gff"
background_dataset: "<sequencing-directory>/resources/background.fasta"

generate:
  consensus_sequences: true
  typing: true
  quality_control_report: true
  phylogeny: true

preprocessing:
  check_size: true
  minimum_size: 100

alignment_bwa:
  bwa_params: "-M"

trimming:
  minimum_length: 30
  minimum_quality: 20
  window_length: 4

coverage_mask:
  required_depth: 15

call_variants:
  maximum_depth: 2000
  minimum_mapping_quality: 30
  minimum_base_quality: 20
  mpileup_parameters: "-B -a INFO/AD,INFO/ADF,INFO/ADR -Ou"
  call_parameters: -mv -Ov --ploidy 1

filter_variants:
  minimum_depth: 15
  minimum_support: 0.5
  minimum_strand_depth: 5

call_consensus:
  consensus_parameters: "--mark-del N"

mlst_profiling:
  scheme: "vcholerae"
  mlst_params: "--quiet --csv --legacy"

tree_building:
  minimum_completeness: 0.75
  outgroup: ""
  iqtree_parameters: -nt AUTO -m TEST -bb 1000
