channels:
  - conda-forge
  - bioconda
dependencies:
  - bc = 1.07.1
  - bcftools = 1.17
  - bedtools = 2.25.0
  - biopython = 1.81
  - bwa = 0.7.17
  - emboss = 6.6.0
  - fastqc
  - figtree
  - filtlong = 0.2.1
  - iqtree=2.2.3
  - mafft = 7.464
  - mlst
  - multiqc
  - pandas
  - qualimap
  - samtools = 1.17
  - snakemake = 7.31.0
  - snp-sites
  - augur
  - ucsc-fatovcf
