# General parameters; point to input files and the like.
run_type: "Illumina"
samples: "input/illumina_sequences.csv"
reference: "resources/vc_reference.fasta"

alignment_bwa:
  bwa_params: "-M"

trimming:
  minimum_length: 30
  minimum_quality: 20
  window_length: 4
