# General parameters; point to input files and the like.
run_type: "ONT"
samples: "input/accession_selected.txt"
path-to-raw-data: "/"
path-to-run-configuration: "/"
reference: "resources/vc_reference.fasta"

# Rule specific parameters
basecalling:
  guppy_params: "-r -v -x auto"

filter_reads:
  keep_percent: 90
  target_bases: 800000000
  filtlong_params: ""

alignment:
  minimap_params: ""

alignment_bwa:
  bwa_params: "-M"

calculate_depth:
  maximum_depth: 10000

filter_vcf:
  minimum_reads: 100
  minimum_support: 0.75

minion_qc:
  format: "png"   # pdf can also be specified, might be useful if X11 not in system


