# General parameters; point to input files and the like.
run_type: "Illumina"
samples: "/home/nate/analysis/2023.07.28_cholera/input/illumina_sequences.csv"
output_directory: "/home/nate/analysis/2023.07.28_cholera/"
reference: "/home/nate/analysis/2023.07.28_cholera/resources/vc_reference.fasta"
reference_genes: "/home/nate/analysis/2023.07.28_cholera/resources/cholera_ref_genes/"
recombinant_mask: "/home/nate/analysis/2023.07.28_cholera/resources/cholera_mask.gff"

alignment_bwa:
  bwa_params: "-M"

trimming:
  minimum_length: 30
  minimum_quality: 20
  window_length: 4

coverage_mask:
  required_depth: 15

call_variants:
  maximum_depth: 2000
  minimum_mapping_quality: 30
  minimum_base_quality: 20
  mpileup_parameters: "-B -a INFO/AD,INFO/ADF,INFO/ADR -Ou"
  call_parameters: -mv -Ov --ploidy 1

filter_variants:
  minimum_depth: 15
  minimum_support: 0.5
  minimum_strand_depth: 5

call_consensus:
  consensus_parameters: "--mark-del N"

mlst_profiling:
  scheme: "vcholerae"
  mlst_params: "--quiet --csv --legacy"
