$schema: "https://json-schema.org/draft/2020-12/schema"

description: Snakemake configuration file
type: object

properties:
  samples:
    description: "Location of metadata for samples being processed by the pipeline."
    type: string
  path-to-raw-data:
    description: "Location of raw data. Typically the run folder off an Illumina or MinION."
    type: string
  path-to-run-configuration:
    description: "Location of sequencing run configuration."
    type: string
  reference:
    description: "Location of reference sequence. Must be in fasta format."
    type: string
    pattern: "^.*\\.(fasta|fa)$"

  # Properties for individual rules.
  basecalling:
    description: "Parameters required for calling bases from raw sequencing signal."
    type: object
    properties:
      guppy_params:
        description: "Parameters to pass to the guppy program"
        type: string
        default: "-r -v -x auto"
    required:
      - guppy_params

  filter_reads:
    description: "Parameters required for filtering raw reads off the sequencer."
    type: object
    properties:
      keep_percent:
        description: "Percentage of good bases to keep."
        type: number
        maximum: 100
        exclusiveMinimum: 0
        default: 90
      target_bases:
        description: "Maximum number of good bases to keep."
        type: integer
        exclusiveMinimum: 0
        default: 800000000
      filtlong_params:
        description: "Parameters to pass on to the filtlong program."
        type: string
        default: ""
    required:
      - keep_percent
      - target_bases
      - filtlong_params

  alignment:
    description: "Parameters for the alignment step."
    type: object
    properties:
      minimap_params:
        description: "Parameters passed to the minimap2 program"
        type: string
        default: ""
    required:
      - minimap_params

  calculate_depth:
    description: "Parameters required when calculating depth for a BAM file."
    type: object
    properties:
      maximum_depth:
        description: "Maximum depth that can be reported at a position."
        type: integer
        exclusiveMinimum: 0
        default: 10000
    required:
      - maximum_depth

  filter_vcf:
    description: "Parameters used to filter variants from VCF files."
    type: object
    properties:
      minimum_reads:
        description: "Variants must be present in at least this many reads to be accepted."
        type: integer
        exclusiveMinimum: 0
        default: 100
      minimum_support:
        description: "Variants must be present in this fraction of reads to be accepted."
        type: number
        exclusiveMinimum: 0
        maximum: 1
        default: 0.75
    required:
      - minimum_reads
      - minimum_support

  minion_qc:
    description: "Parameters for generating the QC report for MinION data."
    type: object
    properties:
      format:
        description: "The output format of the plots generated by minion_qc"
        enum:
          - "png"
          - "pdf"
        default: "png"
    required:
      - format

required:
  - samples
  - path-to-raw-data
  - path-to-run-configuration
  - reference
  - basecalling
  - filter_reads
  - alignment
  - calculate_depth
  - filter_vcf
  - minion_qc
