# General parameters; point to input files.
run_type: "Illumina"
samples: "{{ sample_data }}"
output_directory: "{{ project_path }}"
reference: "vc_reference.fasta"
reference_genes: "resources/cholera_ref_genes/"
recombinant_mask: "resources/cholera_gubbins_mask.gff"
background_dataset: "<background-dataset-path>"

generate:
  consensus_sequences: true
  typing: false
  quality_control_report: true
  phylogeny: false

preprocessing:
  check_size: true
  minimum_size: 100

alignment_bwa:
  bwa_params: "-M"

trimming:
  minimum_length: 30
  minimum_quality: 20
  window_length: 4

coverage_mask:
  required_depth: 10

plot_coverage:
  bin_size: 10000

call_variants:
  maximum_depth: 2000
  minimum_mapping_quality: 30
  minimum_base_quality: 20
  mpileup_parameters: "-B -a INFO/AD,INFO/ADF,INFO/ADR -Ou"
  call_parameters: -mv -Ov --ploidy 1

filter_variants:
  minimum_depth: 10
  minimum_support: 0.5
  minimum_strand_depth: 5

call_consensus:
  consensus_parameters: "--mark-del N"

mlst_profiling:
  scheme: "vcholerae"
  mlst_params: "--quiet --csv --legacy"

antibiotic_resistance:
  database: card

tree_building:
  minimum_completeness: 0.90
  outgroup: ""
  model: "GTR"
  iqtree_parameters: "-bb 1000"

