$schema: "https://json-schema.org/draft/2020-12/schema"

description: Snakemake configuration file for Illumina pipeline
type: object

properties:
  run_type:
    description: "Indicates the type of run being conducted"
    const: "Illumina"
  samples:
    description: "Location of metadata for samples being processed by the pipeline."
    type: string
    pattern: "^.*\\.[ct]sv$"
  output_directory:
    description: "Location to write output files."
    type: string
  reference:
    description: "Location of reference sequence. Must be in fasta format (.fasta|.fa)."
    type: string
    pattern: "^.*\\.(fasta|fa)$"
  reference_genes:
    description: "Location of directory containing reference genes for typing purposes."
    type: string
  recombinant_mask:
    description: "Published list of recombinant sites to mask from consensus sequence. Must be a '.gff' file."
    type: string
    pattern: "^.*\\.gff$"


  alignment_bwa:
    description: "Parameters for the alignment step using BWA."
    type: object
    properties:
      bwa_params:
        description: "Optional parameters passed directly to the bwa program."
        type: string
        default: "-M"
    required:
      - bwa_params

  trimming:
    description: "Parameters required for when trimming alignment."
    type: object
    properties:
      minimum_length:
        description: "Minimum length for a read to be retain after trimming"
        type: integer
        exclusiveMinimum: 0
        default: 30
      minimum_quality:
        description: "Minimum quality threshold in sliding window for bases to be retained"
        type: integer
        exclusiveMinimum: 0
        maximum: 60
        default: 20
      window_length:
        description: "Width of sliding window."
        type: integer
        exclusiveMinimum: 0
        default: 4
    required:
      - minimum_length
      - minimum_quality
      - window_length

  coverage_mask:
    description: "Parameters required for creation of a bed depth file."
    type: object
    properties:
      required_depth:
        description: "Minimum depth at a position"
        type: integer
        minimum: 0
        default: 15
    required:
      - required_depth

  call_variants:
    description: "Parameters required for calling variants from an alignment."
    type: object
    properties:
      maximum_depth:
        description: "Maximum number of reads read at a position."
        type: integer
        exclusiveMinimum: 0
        default: 2000
      minimum_mapping_quality:
        description: "Minimum mapping quality for an alignment to be used."
        type: integer
        minimum: 0
        exclusiveMaximum: 255
        default: 30
      minimum_base_quality:
        description: "Minimum base quality for a base to be considered."
        type: integer
        exclusiveMinimum: 0
        maximum: 60
        default: 20
      mpileup_parameters:
        description: "Parameters passed to the 'bcftools mpileup' command."
        type: string
        default: "-B -a INFO/AD,INFO/ADF,INFO/ADR -Ou"
      call_parameters:
        description: "Paramteres passed to the 'bcftools call' command."
        type: string
        default: "-mv -Ov --ploidy 1"
    required:
      - maximum_depth
      - minimum_mapping_quality
      - minimum_base_quality
      - mpileup_parameters
      - call_parameters

  filter_variants:
    description: "Parameters involved in filtering variants prior to consensus calling."
    type: object
    properties:
      minimum_depth:
        description: "Minimum allelic depth at a position."
        type: integer
        minimum: 0
        default: 15
      minimum_strand_depth:
        description: "Minimum allelic depth on either strand."
        type: integer
        minimum: 0
        default: 5
      minimum_support:
        description: "Minimum number of reads allele must be present in."
        type: number
        exclusiveMinimum: 0
        maximum: 1
        default: 0.5
    required:
      - minimum_depth
      - minimum_strand_depth
      - minimum_support

  call_consensus:
    description: "Parameters passes to the consensus calling step"
    type: object
    properties:
      consensus_parameters:
        description: "Parameters passed to the 'bcftools consensus' program."
        type: string
        default: "--mark-del N"
    required:
      - consensus_parameters

required:
  - run_type
  - samples
  - output_directory
  - reference
  - reference_genes
  - alignment_bwa
  - trimming
  - coverage_mask
  - call_variants
  - filter_variants
  - call_consensus
  - recombinant_mask
