name: Build distribution

on: [ push ]

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build distributions
        shell: bash -l {0}
        run: python -m build

      - name: Publish package to PyPI
        if: github.repository == 'CholGen/bacpage' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
