name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'bacpage.zip'
        exclusions: '*.git* Dockerfile config/*.yaml .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "bacpage.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        body: "Latest release of bioinformatics pipeline."
        tag: "v0.4w"
