name: Test pipeline quickly

on: [ pull_request, push, workflow_dispatch ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment_test.yaml

      - name: Run tests
        run: pytest -k not slow . --no-header --no-summary -q
